# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tmpr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tmpr
  pod 'RxSwift', '5.0.0'
  pod 'RxCocoa', '5.0.0'
  pod 'Alamofire','4.8.2'
  pod 'SwiftyJSON','5.0.0'
  pod 'AlamofireImage','3.5.2'

  target 'tmprTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '5.0.0'
    pod 'RxTest', '5.0.0'
  end

end
