# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tmpr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tmpr ...
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'tmprTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
  end

end
